CREATE TABLE IF NOT EXISTS users(
    id  serial PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(40) NOT NULL,
    password varchar(100) NOT NULL,
    create_at timestamp(3) with time zone DEFAULT LOCALTIMESTAMP(3),
    update_at timestamp(3) with time zone DEFAULT LOCALTIMESTAMP(3),
    enabled boolean NOT NULL
);
CREATE TABLE authorities(
    id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    authority varchar(50) NOT NULL DEFAULT 'guest'
);

CREATE VIEW acelist (
    id serial PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid serial,
    aid smallint
)