CREATE TABLE IF NOT EXISTS users(
    id  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(40) NOT NULL,
    password varchar(100) NOT NULL,
    create_at timestamp(3) with time zone DEFAULT LOCALTIMESTAMP(3),
    update_at timestamp(3) with time zone DEFAULT LOCALTIMESTAMP(3),
    enabled boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS authorities(
    id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    authority varchar(50) NOT NULL DEFAULT 'guest'
);

-- CREATE VIEW acelist (
--     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     uid bigint,
--     aid smallint
-- );
CREATE VIEW acelist AS SELECT u.id AS id, u.id AS uid, a.id AS aid FROM users u CROSS JOIN authorities a;
INSERT into users (username,password,enabled) VALUES ('admin','$2a$10$KVP3B5j.DEWQbUl/JCxtFOYAary6o8eLFWnutHNMvqRx1dkraEpbi',TRUE);