/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories;

@SpringBootApplication
@EnableR2dbcRepositories
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class,args);
    }
}
