/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.example.app.tool.LdTool;

@SpringBootTest
class MessageUtilsTest {
    @Autowired
    private LdTool ldTool;

    @Test void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
    @Test
    public void testEncodePassword() {
        String encodedPass = ldTool.encodePassword("ninia@0210");
        System.out.println("Encoded Password: " + encodedPass);
    }
}
